# Trigger fix
name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Grant execute permission to gradlew
      run: chmod +x ./chatbridge/android/gradlew

    - name: Build Debug APK
      run: ./chatbridge/android/gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ChatBridge-APK
        path: ./chatbridge/android/app/build/outputs/apk/debug/app-debug.apk
